version: '3'
services:
  backend:
    image: backend
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: your-db-host
      POSTGRES_PORT: 5432
      POSTGRES_USER: your-db-username
      POSTGRES_PASSWORD: your-db-password
      POSTGRES_DB: your-db-name

