name: Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: [ master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Lint the codebase
        run: yarn lint

      - name: Test our code
        run: yarn test

      - name: Build
        run: yarn build

      - name: Deploy On DigitalOcean
        uses: appleboy/ssh-action@v0.1.2
        with: 
            host: ${{secrets.SSH_HOST}}
            key: ${{secrets.SSH_KEY}}
            username: ${{secrets.SSH_USERNAME}}

            script:
                cd /var/www/mycargonaut/MyCargonaut-Backend
                git pull origin master
                pm2 start npm --name "backend" -- run start
                pm2 save
